@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>MediaFragment</b> (ebucore:MediaFragment)" as ebucore_MediaFragment [[#ebucore%3AMediaFragment]]
class "<b>Brand</b> (schema:Brand)" as schema_Brand [[../../events/en#schema%3ABrand]]
class "<b>Annotation</b> (ebucore:Annotation)" as ebucore_Annotation [[#ebucore%3AAnnotation]]
class "<b>Archive component</b> (schema:ArchiveComponent)" as schema_ArchiveComponent [[#schema%3AArchiveComponent]]
class "<b>Creative work</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>Audio</b> (haDes:Audio)" as haDes_Audio [[#haDes%3AAudio]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Audio reel</b> (haDes:AudioReel)" as haDes_AudioReel [[#haDes%3AAudioReel]]
class "<b>Physical carrier</b> (haObj:PhysicalCarrier)" as haObj_PhysicalCarrier [[#haObj%3APhysicalCarrier]]
class "<b>Audiovisual carrier</b> (haDes:AudiovisualCarrier)" as haDes_AudiovisualCarrier [[#haDes%3AAudiovisualCarrier]]
class "<b>Physical carrier</b> (haObj:PhysicalCarrier)" as haObj_PhysicalCarrier [[#haObj%3APhysicalCarrier]]
class "<b>Audiovisual carrier representation</b> (haDes:AudiovisualCarrierRepresentation)" as haDes_AudiovisualCarrierRepresentation [[#haDes%3AAudiovisualCarrierRepresentation]]
class "<b>Carrier representation</b> (haObj:CarrierRepresentation)" as haObj_CarrierRepresentation [[#haObj%3ACarrierRepresentation]]
class "<b>Broadcast event</b> (schema:BroadcastEvent)" as schema_BroadcastEvent [[#schema%3ABroadcastEvent]]
class "<b>Event</b> (schema:Event)" as schema_Event [[#schema%3AEvent]]
class "<b>Carrier representation</b> (haObj:CarrierRepresentation)" as haObj_CarrierRepresentation [[#haObj%3ACarrierRepresentation]]
class "<b>Representation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Closed caption</b> (ebucore:ClosedCaptions)" as ebucore_ClosedCaptions [[#ebucore%3AClosedCaptions]]
class "<b>Captioning</b> (ebucore:Captioning)" as ebucore_Captioning [[#ebucore%3ACaptioning]]
class "<b>Collection</b> (schema:Collection)" as schema_Collection [[#schema%3ACollection]]
class "<b>Creative work</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>Concept</b> (skos:Concept)" as skos_Concept [[../../rights/en#skos%3AConcept]]
class "<b>Content partner</b> (haOrg:ContentPartner)" as haOrg_ContentPartner [[../../organizations/en#haOrg%3AContentPartner]]
class "<b>Organization</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>Creative work</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>Thing</b> (schema:Thing)" as schema_Thing [[#schema%3AThing]]
class "<b>Creative work season</b> (schema:CreativeWorkSeason)" as schema_CreativeWorkSeason [[#schema%3ACreativeWorkSeason]]
class "<b>Creative work</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>Creative work series</b> (schema:CreativeWorkSeries)" as schema_CreativeWorkSeries [[#schema%3ACreativeWorkSeries]]
class "<b>Creative work</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>DVD</b> (haDes:DVD)" as haDes_DVD [[#haDes%3ADVD]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>DVD chapter</b> (haDes:DVDChapter)" as haDes_DVDChapter [[#haDes%3ADVDChapter]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Digital representation</b> (haObj:DigitalRepresentation)" as haObj_DigitalRepresentation [[#haObj%3ADigitalRepresentation]]
class "<b>Representation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Episode</b> (schema:Episode)" as schema_Episode [[#schema%3AEpisode]]
class "<b>Creative work</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>File</b> (premis:File)" as premis_File [[#premis%3AFile]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Film</b> (haDes:Film)" as haDes_Film [[#haDes%3AFilm]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Film carrier representation</b> (haDes:FilmCarrierRepresentation)" as haDes_FilmCarrierRepresentation [[#haDes%3AFilmCarrierRepresentation]]
class "<b>Carrier representation</b> (haObj:CarrierRepresentation)" as haObj_CarrierRepresentation [[#haObj%3ACarrierRepresentation]]
class "<b>Image</b> (haDes:Image)" as haDes_Image [[#haDes%3AImage]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Image reel</b> (haDes:ImageReel)" as haDes_ImageReel [[#haDes%3AImageReel]]
class "<b>Physical carrier</b> (haObj:PhysicalCarrier)" as haObj_PhysicalCarrier [[#haObj%3APhysicalCarrier]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Newspaper</b> (schema:Newspaper)" as schema_Newspaper [[#schema%3ANewspaper]]
class "<b>Creative work series</b> (schema:CreativeWorkSeries)" as schema_CreativeWorkSeries [[#schema%3ACreativeWorkSeries]]
class "<b>Newspaper issue</b> (haDes:NewspaperIssue)" as haDes_NewspaperIssue [[#haDes%3ANewspaperIssue]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Newspaper issue page</b> (haDes:NewspaperIssuePage)" as haDes_NewspaperIssuePage [[#haDes%3ANewspaperIssuePage]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Open captions</b> (ebucore:OpenCaptions)" as ebucore_OpenCaptions [[#ebucore%3AOpenCaptions]]
class "<b>Captioning</b> (ebucore:Captioning)" as ebucore_Captioning [[#ebucore%3ACaptioning]]
class "<b>Open captions</b> (ebucore:OpenCaptions)" as ebucore_OpenCaptions [[#ebucore%3AOpenCaptions]]
class "<b>Captioning</b> (ebucore:Captioning)" as ebucore_Captioning [[#ebucore%3ACaptioning]]
class "<b>Organization</b> (org:Organization)" as org_Organization [[../../organizations/en#org%3AOrganization]]
class "<b>Performance role</b> (schema:PerformanceRole)" as schema_PerformanceRole [[#schema%3APerformanceRole]]
class "<b>Role</b> (schema:Role)" as schema_Role [[#schema%3ARole]]
class "<b>Person</b> (schema:Person)" as schema_Person [[../../organizations/en#schema%3APerson]]
class "<b>Thing</b> (schema:Thing)" as schema_Thing [[#schema%3AThing]]
class "<b>Physical carrier</b> (haObj:PhysicalCarrier)" as haObj_PhysicalCarrier [[#haObj%3APhysicalCarrier]]
class "<b>Storage location</b> (premis:StorageLocation)" as premis_StorageLocation [[#premis%3AStorageLocation]]
class "<b>Place</b> (schema:Place)" as schema_Place [[#schema%3APlace]]
class "<b>Thing</b> (schema:Thing)" as schema_Thing [[#schema%3AThing]]
class "<b>Quantitative Value</b> (schema:QuantitativeValue)" as schema_QuantitativeValue [[#schema%3AQuantitativeValue]]
class "<b>Thing</b> (schema:Thing)" as schema_Thing [[#schema%3AThing]]
class "<b>Representation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Role</b> (schema:Role)" as schema_Role [[#schema%3ARole]]
class "<b>Thing</b> (schema:Thing)" as schema_Thing [[#schema%3AThing]]
class "<b>Role name</b> (haDes:RoleName)" as haDes_RoleName [[#haDes%3ARoleName]]
class "<b>Concept</b> (skos:Concept)" as skos_Concept [[#skos%3AConcept]]
class "<b>Silent film</b> (haDes:SilentFilm)" as haDes_SilentFilm [[#haDes%3ASilentFilm]]
class "<b>Film</b> (haDes:Film)" as haDes_Film [[#haDes%3AFilm]]
class "<b>Sound film</b> (haDes:SoundFilm)" as haDes_SoundFilm [[#haDes%3ASoundFilm]]
class "<b>Film</b> (haDes:Film)" as haDes_Film [[#haDes%3AFilm]]
class "<b>Text Annotation</b> (ebucore:TextAnnotation)" as ebucore_TextAnnotation [[#ebucore%3ATextAnnotation]]
class "<b>Annotation</b> (ebucore:Annotation)" as ebucore_Annotation [[#ebucore%3AAnnotation]]
class "<b>Thing</b> (schema:Thing)" as schema_Thing [[#schema%3AThing]]
class "<b>Video</b> (haDes:Video)" as haDes_Video [[#haDes%3AVideo]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Written work carrier representation</b> (haDes:WrittenWorkCarrierRepresentation)" as haDes_WrittenWorkCarrierRepresentation [[#haDes%3AWrittenWorkCarrierRepresentation]]
class "<b>Carrier representation</b> (haObj:CarrierRepresentation)" as haObj_CarrierRepresentation [[#haObj%3ACarrierRepresentation]]


ebucore_MediaFragment : end time : <i>xsd:time</i> [0..1]
ebucore_MediaFragment : height : <i>xsd:integer</i> [0..1]
ebucore_MediaFragment : region delimiter (x-axis) : <i>xsd:integer</i> [0..1]
ebucore_MediaFragment : region delimiter (y-axis) : <i>xsd:integer</i> [0..1]
ebucore_MediaFragment : start time : <i>xsd:time</i> [0..1]
ebucore_MediaFragment : width : <i>xsd:integer</i> [0..1]
ebucore_MediaFragment --> premis_File :is Media Fragment Of [0..*]  > 






ebucore_Annotation : annotation  person subject : <i>IRI</i> [0..1]
ebucore_Annotation : annotation confidence : <i>xsd:decimal</i> [1..1]
ebucore_Annotation : annotation subject : <i>IRI</i> [1..1]

ebucore_Annotation --> ebucore_MediaFragment :annotates [1..*]  > 
ebucore_Annotation --> premis_File :annotation target [1..1]  > 
ebucore_Annotation --> skos_Concept :annotation type [0..1]  > 


schema_ArchiveComponent --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_ArchiveComponent : description : <i>rdf:langString</i> [0..*]
schema_ArchiveComponent : name : <i>rdf:langString</i> [1..*]
schema_ArchiveComponent --> premis_IntellectualEntity :has part [0..*]  > 

schema_ArchiveComponent --> schema_ArchiveComponent :has part [0..*]  \lis part of [0..*]  > 

haDes_Audio --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_Audio : broadcasting organization : <i>org:Organization</i> [0..1]
haDes_Audio --> haDes_AudiovisualCarrierRepresentation :has carrier copy [0..1]  > 


haDes_AudioReel --|> haObj_PhysicalCarrier #blue;line.dotted;text:blue


haDes_AudiovisualCarrier --|> haObj_PhysicalCarrier #blue;line.dotted;text:blue

haDes_AudiovisualCarrier : audio noise reduction : <i>xsd:string</i> [0..1]
haDes_AudiovisualCarrier --> skos_Concept :audio recording speed [0..1]  \liec-60094 type [0..1]  > 


haDes_AudiovisualCarrierRepresentation --|> haObj_CarrierRepresentation #blue;line.dotted;text:blue

haDes_AudiovisualCarrierRepresentation : number of audio channels : <i>xsd:nonNegativeInteger</i> [0..1]
haDes_AudiovisualCarrierRepresentation : number of audio tracks : <i>xsd:nonNegativeInteger</i> [0..1]
haDes_AudiovisualCarrierRepresentation --> haDes_AudiovisualCarrier :stored at [1..*]  > 


schema_BroadcastEvent --|> schema_Event #blue;line.dotted;text:blue


haObj_CarrierRepresentation --|> premis_Representation #blue;line.dotted;text:blue


ebucore_ClosedCaptions --|> ebucore_Captioning #blue;line.dotted;text:blue


schema_Collection --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_Collection : collection size : <i>xsd:integer</i> [0..*]
schema_Collection : description : <i>rdf:langString</i> [0..*]
schema_Collection : identifier : <i>xsd:string</i> [0..1]
schema_Collection : name : <i>rdf:langString</i> [1..*]
schema_Collection --> haObj_PhysicalCarrier :has part [0..*]  > 
schema_Collection --> premis_IntellectualEntity :has part [0..*]  > 






haOrg_ContentPartner --|> org_Organization #blue;line.dotted;text:blue


schema_CreativeWork --|> schema_Thing #blue;line.dotted;text:blue


schema_CreativeWorkSeason --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_CreativeWorkSeason : description : <i>rdf:langString</i> [0..*]
schema_CreativeWorkSeason : identifier : <i>xsd:string</i> [0..1]
schema_CreativeWorkSeason : name : <i>rdf:langString</i> [1..*]
schema_CreativeWorkSeason : season number : <i>xsd:integer</i> [0..*]
schema_CreativeWorkSeason --> premis_IntellectualEntity :has part [0..*]  > 

schema_CreativeWorkSeason --> schema_CreativeWork :has part [0..*]  > 
schema_CreativeWorkSeason --> schema_CreativeWorkSeries :is part of [0..*]  > 



schema_CreativeWorkSeries --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_CreativeWorkSeries : description : <i>rdf:langString</i> [0..*]
schema_CreativeWorkSeries : identifier : <i>xsd:string</i> [0..1]
schema_CreativeWorkSeries : name : <i>rdf:langString</i> [1..*]
schema_CreativeWorkSeries : position : <i>xsd:integer</i> [0..*]
schema_CreativeWorkSeries --> premis_IntellectualEntity :has part [0..*]  > 

schema_CreativeWorkSeries --> schema_CreativeWork :has part [0..*]  > 
schema_CreativeWorkSeries --> schema_CreativeWorkSeries :is part of [0..*]  > 



haDes_DVD --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_DVD : broadcasting organization : <i>org:Organization</i> [0..1]
haDes_DVD --> haDes_AudiovisualCarrierRepresentation :has carrier copy [0..1]  > 
haDes_DVD --> haDes_DVDChapter :has part [0..*]  > 


haDes_DVDChapter --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_DVDChapter : chapter number : <i>xsd:nonNegativeInteger</i> [1..1]
haDes_DVDChapter --> haDes_DVD :is part of [1..1]  > 


haObj_DigitalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_DigitalRepresentation : caption : <i>xsd:string</i> [0..1]
haObj_DigitalRepresentation : date created : <i>edtf:EDTF-level0 | edtf:EDTF-level1 | edtf:EDTF-level2</i> [0..1]
haObj_DigitalRepresentation : date published : <i>edtf:EDTF-level0 | edtf:EDTF-level1 | edtf:EDTF-level2</i> [0..1]
haObj_DigitalRepresentation : in language : <i>xsd:string</i> [0..*]
haObj_DigitalRepresentation : transcription : <i>xsd:string</i> [0..1]



haObj_DigitalRepresentation --> schema_Role :creator [0..*]  > 


schema_Episode --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_Episode : description : <i>rdf:langString</i> [0..*]
schema_Episode : name : <i>rdf:langString</i> [1..*]
schema_Episode --> premis_IntellectualEntity :has part [0..*]  > 


premis_File --|> premis_Object #blue;line.dotted;text:blue

premis_File : date created : <i>edtf:EDTF-level0 | edtf:EDTF-level1 | edtf:EDTF-level2</i> [1..1]
premis_File : description : <i>rdf:langString</i> [0..*]
premis_File : duration : <i>xsd:duration</i> [0..1]
premis_File : identifier : <i>xsd:string</i> [0..1]
premis_File : name : <i>rdf:langString</i> [1..*]
premis_File : thumbnail : <i>IRI</i> [0..1]

premis_File --> ebucore_ClosedCaptions :captioning [0..*]  > 
premis_File --> ebucore_MediaFragment :has media fragment [0..*]  > 



premis_File --> premis_File :captioning [0..*]  > 




haDes_Film --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_Film : broadcasting organization : <i>org:Organization</i> [0..1]
haDes_Film --> haDes_FilmCarrierRepresentation :has carrier copy [1..1]  > 


haDes_FilmCarrierRepresentation --|> haObj_CarrierRepresentation #blue;line.dotted;text:blue

haDes_FilmCarrierRepresentation : lost audio reels : <i>xsd:boolean</i> [0..1]
haDes_FilmCarrierRepresentation : lost image reels : <i>xsd:boolean</i> [0..1]
haDes_FilmCarrierRepresentation : number of lost audio reels : <i>xsd:nonNegativeInteger</i> [0..1]
haDes_FilmCarrierRepresentation : number of lost image reels : <i>xsd:nonNegativeInteger</i> [0..1]
haDes_FilmCarrierRepresentation : number of reels : <i>xsd:nonNegativeInteger</i> [0..1]
haDes_FilmCarrierRepresentation --> haDes_AudioReel :stored at [1..*]  > 
haDes_FilmCarrierRepresentation --> haDes_ImageReel :stored at [1..*]  > 



haDes_Image --|> premis_IntellectualEntity #blue;line.dotted;text:blue


haDes_ImageReel --|> haObj_PhysicalCarrier #blue;line.dotted;text:blue

haDes_ImageReel --> ebucore_OpenCaptions :has (embedded) captioning [0..*]  > 
haDes_ImageReel --> skos_Concept :coloring type [0..*]  > 

premis_IntellectualEntity --|> premis_Object #blue;line.dotted;text:blue

premis_IntellectualEntity : about : <i>IRI</i> [0..*]
premis_IntellectualEntity : abstract : <i>rdf:langString</i> [0..*]
premis_IntellectualEntity : alternate name : <i>rdf:langString</i> [0..*]
premis_IntellectualEntity : art medium : <i>rdf:langString</i> [0..*]
premis_IntellectualEntity : artform : <i>rdf:langString</i> [0..*]
premis_IntellectualEntity : castmembers : <i>xsd:string</i> [0..1]
premis_IntellectualEntity : copyright notice : <i>xsd:string</i> [0..*]
premis_IntellectualEntity : copyright year : <i>xsd:integer</i> [0..*]
premis_IntellectualEntity : credit text : <i>rdf:langString</i> [0..*]
premis_IntellectualEntity : date available : <i>xsd:dateTime</i> [0..1]
premis_IntellectualEntity : date created : <i>edtf:EDTF-level0 | edtf:EDTF-level1 | edtf:EDTF-level2</i> [1..1]
premis_IntellectualEntity : date published : <i>edtf:EDTF-level0 | edtf:EDTF-level1 | edtf:EDTF-level2</i> [0..1]
premis_IntellectualEntity : description : <i>rdf:langString</i> [0..*]
premis_IntellectualEntity : duration : <i>xsd:duration</i> [0..1]
premis_IntellectualEntity : format : <i>xsd:string</i> [1..1]
premis_IntellectualEntity : genre : <i>rdf:langString</i> [0..*]
premis_IntellectualEntity : identifier : <i>xsd:string</i> [1..1]
premis_IntellectualEntity : in language : <i>xsd:string</i> [0..*]
premis_IntellectualEntity : keywords : <i>rdf:langString</i> [0..*]
premis_IntellectualEntity : name : <i>rdf:langString</i> [1..*]
premis_IntellectualEntity : object type : <i>xsd:string</i> [0..1]
premis_IntellectualEntity : rights information : <i>rdf:langString</i> [0..*]
premis_IntellectualEntity : synopsis : <i>xsd:string</i> [0..1]
premis_IntellectualEntity : temporal : <i>rdf:langString</i> [0..*]




premis_IntellectualEntity --> haOrg_ContentPartner :maintainer [1..1]  > 
premis_IntellectualEntity --> org_Organization :copyright holder [0..*]  \llicense distributor [0..*]  > 

premis_IntellectualEntity --> schema_BroadcastEvent :is part of [0..*]  > 
premis_IntellectualEntity --> schema_CreativeWork :is part of [0..*]  > 
premis_IntellectualEntity --> schema_PerformanceRole :actor [0..*]  > 
premis_IntellectualEntity --> schema_Person :copyright holder [0..*]  \llicense distributor [0..*]  > 
premis_IntellectualEntity --> schema_Place :spatial [0..*]  > 
premis_IntellectualEntity --> schema_QuantitativeValue :depth [0..1]  \lheight [0..1]  \lwidth [0..1]  > 
premis_IntellectualEntity --> schema_Role :contributor [0..*]  \lcreator [0..*]  \lexecutor [0..*]  \lproducer [0..*]  \lpublisher [0..*]  > 
premis_IntellectualEntity --> schema_Thing :copyright holder [0..*]  \llicense distributor [0..*]  \lmentions [0..*]  > 
premis_IntellectualEntity --> skos_Concept :license [0..*]  > 





schema_Newspaper --|> schema_CreativeWorkSeries #blue;line.dotted;text:blue

schema_Newspaper : abraham identifier : <i>xsd:string</i> [1..1]
schema_Newspaper : alternate name : <i>rdf:langString</i> [0..*]
schema_Newspaper : end date : <i>xsd:dateTime</i> [0..1]
schema_Newspaper : name : <i>rdf:langString</i> [1..*]
schema_Newspaper : start date : <i>xsd:dateTime</i> [0..1]

schema_Newspaper --> schema_Newspaper :preceded by [0..1]  \lsucceeded by [0..1]  \lsupplement [0..1]  \lsupplement to [0..1]  > 
schema_Newspaper --> schema_Place :location created [0..1]  > 
schema_Newspaper --> schema_Role :publisher [0..1]  > 



haDes_NewspaperIssue --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_NewspaperIssue : issue number : <i>xsd:string</i> [0..1]
haDes_NewspaperIssue : number of pages : <i>xsd:nonNegativeInteger</i> [0..1]
haDes_NewspaperIssue --> haDes_WrittenWorkCarrierRepresentation :has carrier copy [0..1]  > 
haDes_NewspaperIssue --> schema_Newspaper :is part of [0..1]  > 
haDes_NewspaperIssue --> skos_Concept :frequency of issuance [0..1]  \lpublication type [0..1]  > 



haDes_NewspaperIssuePage --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_NewspaperIssuePage : page number : <i>xsd:nonNegativeInteger</i> [0..1]
haDes_NewspaperIssuePage --> haDes_NewspaperIssue :is part of [1..1]  > 


ebucore_OpenCaptions --|> ebucore_Captioning #blue;line.dotted;text:blue

ebucore_OpenCaptions : in language : <i>xsd:string</i> [0..*]


ebucore_OpenCaptions --|> ebucore_Captioning #blue;line.dotted;text:blue

ebucore_OpenCaptions : in language : <i>xsd:string</i> [0..*]




schema_PerformanceRole --|> schema_Role #blue;line.dotted;text:blue

schema_PerformanceRole : character name : <i>xsd:string</i> [0..1]


schema_Person --|> schema_Thing #blue;line.dotted;text:blue


haObj_PhysicalCarrier --|> premis_StorageLocation #blue;line.dotted;text:blue

haObj_PhysicalCarrier : description : <i>rdf:langString</i> [0..*]
haObj_PhysicalCarrier : identifier : <i>xsd:string</i> [1..1]
haObj_PhysicalCarrier : material : <i>xsd:string</i> [0..1]
haObj_PhysicalCarrier : material extent : <i>xsd:string</i> [0..1]
haObj_PhysicalCarrier : name : <i>rdf:langString</i> [1..*]

haObj_PhysicalCarrier --> schema_Brand :brand [0..1]  > 
haObj_PhysicalCarrier --> schema_QuantitativeValue :depth [0..1]  \lheight [0..1]  \lwidth [0..1]  > 
haObj_PhysicalCarrier --> skos_Concept :preservation problem [0..*]  > 


schema_Place --|> schema_Thing #blue;line.dotted;text:blue

schema_Place : description : <i>rdf:langString</i> [0..*]
schema_Place : name : <i>rdf:langString</i> [1..*]

schema_Place --> schema_Place :is contained in place [0..*]  > 

schema_QuantitativeValue --|> schema_Thing #blue;line.dotted;text:blue

schema_QuantitativeValue : unit code : <i>xsd:string</i> [1..1]
schema_QuantitativeValue : unit text : <i>xsd:string</i> [0..1]
schema_QuantitativeValue : value : <i>xsd:float</i> [1..1]



premis_Representation --|> premis_Object #blue;line.dotted;text:blue

premis_Representation : description : <i>rdf:langString</i> [0..*]
premis_Representation : identifier : <i>xsd:string</i> [0..1]
premis_Representation : name : <i>rdf:langString</i> [1..*]



schema_Role --|> schema_Thing #blue;line.dotted;text:blue

schema_Role : role name : <i>xsd:string</i> [1..1]
schema_Role --> haDes_RoleName :role name [1..1]  > 
schema_Role --> org_Organization :actor [0..1]  \lcontributor [0..1]  \lcreator [0..1]  \lexecutor [0..1]  \lproducer [0..1]  \lpublisher [0..1]  > 
schema_Role --> schema_Person :actor [0..1]  \lcontributor [0..1]  \lcreator [0..1]  \lexecutor [0..1]  \lproducer [0..1]  \lpublisher [0..1]  > 
schema_Role --> schema_Thing :actor [0..1]  \lcontributor [0..1]  \lcreator [0..1]  \lexecutor [0..1]  \lproducer [0..1]  \lpublisher [0..1]  > 


haDes_RoleName --|> skos_Concept #blue;line.dotted;text:blue


haDes_SilentFilm --|> haDes_Film #blue;line.dotted;text:blue


haDes_SoundFilm --|> haDes_Film #blue;line.dotted;text:blue


ebucore_TextAnnotation --|> ebucore_Annotation #blue;line.dotted;text:blue



schema_Thing : description : <i>rdf:langString</i> [0..*]
schema_Thing : name : <i>rdf:langString</i> [1..*]


haDes_Video --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_Video : broadcasting organization : <i>org:Organization</i> [0..1]
haDes_Video --> haDes_AudiovisualCarrierRepresentation :has carrier copy [0..1]  > 


haDes_WrittenWorkCarrierRepresentation --|> haObj_CarrierRepresentation #blue;line.dotted;text:blue

haDes_WrittenWorkCarrierRepresentation --> skos_Concept :production method [0..1]  > 


hide circle
hide methods
hide empty members
@enduml


