@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>Carrier representation</b> (haObj:CarrierRepresentation)" as haObj_CarrierRepresentation [[#haObj%3ACarrierRepresentation]]
class "<b>Representation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Concept</b> (skos:Concept)" as skos_Concept [[../../rights/en#skos%3AConcept]]
class "<b>Newspaper</b> (schema:Newspaper)" as schema_Newspaper [[#schema%3ANewspaper]]
class "<b>Creative work series</b> (schema:CreativeWorkSeries)" as schema_CreativeWorkSeries [[#schema%3ACreativeWorkSeries]]
class "<b>Newspaper edition</b> (haDes:NewspaperIssue)" as haDes_NewspaperIssue [[#haDes%3ANewspaperIssue]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Newspaper issue page</b> (haDes:NewspaperIssuePage)" as haDes_NewspaperIssuePage [[#haDes%3ANewspaperIssuePage]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Place</b> (schema:Place)" as schema_Place [[../../description/en#schema%3APlace]]
class "<b>Thing</b> (schema:Thing)" as schema_Thing [[#schema%3AThing]]
class "<b>Role</b> (schema:Role)" as schema_Role [[../../description/en#schema%3ARole]]
class "<b>Thing</b> (schema:Thing)" as schema_Thing [[#schema%3AThing]]

haObj_CarrierRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_CarrierRepresentation --> skos_Concept :production method [0..1]  > 



schema_Newspaper --|> schema_CreativeWorkSeries #blue;line.dotted;text:blue

schema_Newspaper : abraham identifier : <i>xsd:string</i> [1..1]
schema_Newspaper : alternate name : <i>rdf:langString</i> [0..*]
schema_Newspaper : end date : <i>xsd:dateTime</i> [0..1]
schema_Newspaper : name : <i>rdf:langString</i> [1..*]
schema_Newspaper : start date : <i>xsd:dateTime</i> [0..1]

schema_Newspaper --> schema_Newspaper :preceded by [0..1]  \lsucceeded by [0..1]  \lsupplement [0..1]  \lsupplement to [0..1]  > 
schema_Newspaper --> schema_Place :location created [0..1]  > 
schema_Newspaper --> schema_Role :publisher [0..1]  > 



haDes_NewspaperIssue --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_NewspaperIssue : issue number : <i>xsd:string</i> [0..1]
haDes_NewspaperIssue : number of pages : <i>xsd:nonNegativeInteger</i> [0..1]
haDes_NewspaperIssue --> haObj_CarrierRepresentation :has carrier copy [0..1]  > 
haDes_NewspaperIssue --> schema_Newspaper :is part of [0..1]  > 
haDes_NewspaperIssue --> skos_Concept :frequency of issuance [0..1]  \lpublication type [0..1]  > 



haDes_NewspaperIssuePage --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_NewspaperIssuePage : page number : <i>xsd:nonNegativeInteger</i> [0..1]
haDes_NewspaperIssuePage --> haDes_NewspaperIssue :is part of [1..1]  > 


schema_Place --|> schema_Thing #blue;line.dotted;text:blue


schema_Role --|> schema_Thing #blue;line.dotted;text:blue



hide circle
hide methods
hide empty members
@enduml


